/**
 * Role Configuration - Defines all system roles and their permissions
 */

const ROLES = {
    NEW_HIRE: 'NewHire',
    CONSULTANT: 'Consultant',
    SENIOR_CONSULTANT: 'SeniorConsultant',
    PROJECT_MANAGER: 'ProjectManager',
    KNOWLEDGE_CHAMPION: 'KnowledgeChampion',
    KNOWLEDGE_GOVERNANCE_COUNCIL: 'KnowledgeGovernanceCouncil',
    IT_INFRASTRUCTURE: 'ITInfrastructure'
};

const ROLE_HIERARCHY = [
    ROLES.NEW_HIRE,
    ROLES.CONSULTANT,
    ROLES.SENIOR_CONSULTANT,
    ROLES.PROJECT_MANAGER,
    ROLES.KNOWLEDGE_CHAMPION,
    ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL,
    ROLES.IT_INFRASTRUCTURE
];

const PERMISSIONS = {
    // Content permissions
    CREATE_CONTENT: [ROLES.CONSULTANT, ROLES.SENIOR_CONSULTANT, ROLES.PROJECT_MANAGER, ROLES.KNOWLEDGE_CHAMPION, ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],
    VIEW_CONTENT: Object.values(ROLES),
    EDIT_OWN_CONTENT: [ROLES.CONSULTANT, ROLES.SENIOR_CONSULTANT, ROLES.PROJECT_MANAGER, ROLES.KNOWLEDGE_CHAMPION, ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],
    DELETE_CONTENT: [ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],

    // Review permissions
    REVIEW_CONTENT: [ROLES.SENIOR_CONSULTANT, ROLES.PROJECT_MANAGER, ROLES.KNOWLEDGE_CHAMPION, ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],
    APPROVE_CONTENT: [ROLES.SENIOR_CONSULTANT, ROLES.PROJECT_MANAGER, ROLES.KNOWLEDGE_CHAMPION, ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],

    // Admin permissions
    MANAGE_USERS: [ROLES.IT_INFRASTRUCTURE],
    VIEW_AUDIT_LOGS: [ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],
    MANAGE_METADATA_RULES: [ROLES.KNOWLEDGE_GOVERNANCE_COUNCIL, ROLES.IT_INFRASTRUCTURE],
    VIEW_SYSTEM_STATS: [ROLES.IT_INFRASTRUCTURE],

    // Training permissions
    ACCESS_TRAINING: [ROLES.NEW_HIRE],
    MANAGE_TRAINING: [ROLES.KNOWLEDGE_CHAMPION, ROLES.IT_INFRASTRUCTURE]
};

const hasPermission = (userRole, permission) => {
    const allowedRoles = PERMISSIONS[permission];
    if (!allowedRoles) return false;
    return allowedRoles.includes(userRole);
};

const isRoleAtLeast = (userRole, requiredRole) => {
    const userIndex = ROLE_HIERARCHY.indexOf(userRole);
    const requiredIndex = ROLE_HIERARCHY.indexOf(requiredRole);
    return userIndex >= requiredIndex;
};

module.exports = {
    ROLES,
    ROLE_HIERARCHY,
    PERMISSIONS,
    hasPermission,
    isRoleAtLeast
};
